from_latest_tag = false
ignore_merge_commits = true
disable_changelog = false
generate_mono_repository_global_tag = true
branch_whitelist = []
skip_ci = "[skip ci]"
skip_untracked = false
pre_bump_hooks = []
post_bump_hooks = []
pre_package_bump_hooks = []
post_package_bump_hooks = []

[git_hooks]

[commit_types]
improvement = { changelog_title = "Improvements", bump_patch = true }
chore = { changelog_title = "Chore", omit_from_changelog = false }
ci = { changelog_title = "", omit_from_changelog = true }
perf = { changelog_title = "", omit_from_changelog = true }

[changelog]
path = "CHANGELOG.md"
remote = "github.com"
repository = "oracle-docker"
owner = "witcom-gmbh"
authors = [
    { signature = "Carsten Buchberger", username = "iceman91176" }
]

[bump_profiles]

[packages]
oracle-openjdk = { path = "oracle-openjdk", public_api = false }
oracle-sql-plus = { path = "oracle-sql-plus", public_api = false }
oracle-sqldeveloper = { path = "oracle-sqldeveloper", public_api = false }
